package demo.client.shared;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@org.kie.api.definition.type.Label("Address")
public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ID #")
   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ADDRESS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ADDRESS_ID_SEQ", name = "ADDRESS_ID_GENERATOR")
   private Long id;

   @org.kie.api.definition.type.Label("Street Name")
   @org.hibernate.validator.constraints.NotEmpty
   private String street;

   @org.kie.api.definition.type.Label("Num #")
   private Integer num;

   @org.kie.api.definition.type.Label("CP")
   @org.hibernate.validator.constraints.NotEmpty
   private String cp;

   @org.kie.api.definition.type.Label("City")
   @org.hibernate.validator.constraints.NotEmpty
   private String city;

   @org.kie.api.definition.type.Label("Country")
   private String country;

   public Address()
   {
   }

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   public String getStreet()
   {
      return this.street;
   }

   public void setStreet(String street)
   {
      this.street = street;
   }

   public Integer getNum()
   {
      return this.num;
   }

   public void setNum(Integer num)
   {
      this.num = num;
   }

   public String getCp()
   {
      return this.cp;
   }

   public void setCp(String cp)
   {
      this.cp = cp;
   }

   public String getCity()
   {
      return this.city;
   }

   public void setCity(String city)
   {
      this.city = city;
   }

   public String getCountry()
   {
      return this.country;
   }

   public void setCountry(String country)
   {
      this.country = country;
   }

   public Address(Long id, String street,
         Integer num, String cp, String city,
         String country)
   {
      this.id = id;
      this.street = street;
      this.num = num;
      this.cp = cp;
      this.city = city;
      this.country = country;
   }

}
